import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "./MainHeader";

/*
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
*/

export const metadata: Metadata = {
  title: "PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head />
      <body className="overflow-clip">
        <div className="main">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
